---
driver:
  name: docker

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[django-cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
  - name: install_pip
    run_list:
      - recipe[django-cookbook::install_pip]
    verifier:
      inspec_tests:
        - test/integration/pip
    attributes:
  - name: install_virtualenv
    run_list:
      - recipe[django-cookbook::install_virtualenv]
    verifier:
      inspec_tests:
        - test/integration/virtualenv
    attributes:
